// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Chantier "environnement de staging" (14/09) : bascule automatique sur le
// projet Supabase de staging quand les variables d'env VITE_SUPABASE_URL /
// VITE_SUPABASE_PUBLISHABLE_KEY sont definies (c'est le cas sur les
// deploiements Vercel Preview de la branche `staging`). En prod (branche
// main), ces variables ne sont pas definies sur Vercel : on retombe sur les
// valeurs historiques en dur ci-dessous, donc AUCUN changement de
// comportement pour la prod.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://cvgosywcwqmsegdgjpqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_pGVcNwQvTDsIMu4G-NC43A_K2llTneL";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Demande Olivier (23/09, sécurité) : une session ne doit plus survivre à la
// fermeture du navigateur/onglet sans déconnexion explicite (formateur ET
// client) — utile notamment sur poste partagé. sessionStorage remplace
// localStorage : la session survit toujours aux rechargements/navigations
// DANS le même onglet (persistSession reste true), mais disparaît dès que
// l'onglet/le navigateur est fermé, sans action supplémentaire à coder.
// Revers assumé : ouvrir l'appli dans un NOUVEL onglet ne partage plus la
// session d'un onglet déjà connecté (chaque onglet redemande une connexion),
// contrairement au comportement précédent avec localStorage.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
